# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.aether.v1 import aether_pb2 as proto_dot_aether_dot_v1_dot_aether__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/aether/v1/aether_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ActorServiceStub(object):
    """============================================================
    Actor Service
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/aether.server.v1.ActorService/Register',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.RegisterActorRequest.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.ActorInfo.FromString,
                _registered_method=True)
        self.Unregister = channel.unary_unary(
                '/aether.server.v1.ActorService/Unregister',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.UnregisterActorRequest.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.UnregisterResponse.FromString,
                _registered_method=True)
        self.GetActor = channel.unary_unary(
                '/aether.server.v1.ActorService/GetActor',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.GetActorRequest.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.ActorInfo.FromString,
                _registered_method=True)
        self.ListActors = channel.unary_unary(
                '/aether.server.v1.ActorService/ListActors',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.ListActorsRequest.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.ListActorsResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/aether.server.v1.ActorService/Heartbeat',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class ActorServiceServicer(object):
    """============================================================
    Actor Service
    ============================================================

    """

    def Register(self, request, context):
        """Register a new actor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unregister(self, request, context):
        """Unregister an actor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActor(self, request, context):
        """Get a single actor's info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActors(self, request, context):
        """List actors with optional filters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat (keep-alive for an actor)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.RegisterActorRequest.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.ActorInfo.SerializeToString,
            ),
            'Unregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Unregister,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.UnregisterActorRequest.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.UnregisterResponse.SerializeToString,
            ),
            'GetActor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActor,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.GetActorRequest.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.ActorInfo.SerializeToString,
            ),
            'ListActors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActors,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.ListActorsRequest.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.ListActorsResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.HeartbeatRequest.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aether.server.v1.ActorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aether.server.v1.ActorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActorService(object):
    """============================================================
    Actor Service
    ============================================================

    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.ActorService/Register',
            proto_dot_aether_dot_v1_dot_aether__pb2.RegisterActorRequest.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.ActorInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.ActorService/Unregister',
            proto_dot_aether_dot_v1_dot_aether__pb2.UnregisterActorRequest.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.UnregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.ActorService/GetActor',
            proto_dot_aether_dot_v1_dot_aether__pb2.GetActorRequest.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.ActorInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.ActorService/ListActors',
            proto_dot_aether_dot_v1_dot_aether__pb2.ListActorsRequest.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.ListActorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.ActorService/Heartbeat',
            proto_dot_aether_dot_v1_dot_aether__pb2.HeartbeatRequest.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MessageServiceStub(object):
    """============================================================
    Message Service
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Send = channel.unary_unary(
                '/aether.server.v1.MessageService/Send',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.DeliveryReceipt.FromString,
                _registered_method=True)
        self.GetPending = channel.unary_unary(
                '/aether.server.v1.MessageService/GetPending',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.GetPendingMessagesRequest.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.GetPendingMessagesResponse.FromString,
                _registered_method=True)


class MessageServiceServicer(object):
    """============================================================
    Message Service
    ============================================================

    """

    def Send(self, request, context):
        """Send a message to an actor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPending(self, request, context):
        """Get pending messages for an actor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.SendMessageRequest.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.DeliveryReceipt.SerializeToString,
            ),
            'GetPending': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPending,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.GetPendingMessagesRequest.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.GetPendingMessagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aether.server.v1.MessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aether.server.v1.MessageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageService(object):
    """============================================================
    Message Service
    ============================================================

    """

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.MessageService/Send',
            proto_dot_aether_dot_v1_dot_aether__pb2.SendMessageRequest.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.DeliveryReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPending(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.MessageService/GetPending',
            proto_dot_aether_dot_v1_dot_aether__pb2.GetPendingMessagesRequest.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.GetPendingMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StateServiceStub(object):
    """============================================================
    State Service
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/aether.server.v1.StateService/GetState',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.GetStateRequest.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.GetStateResponse.FromString,
                _registered_method=True)
        self.SetState = channel.unary_unary(
                '/aether.server.v1.StateService/SetState',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.SetStateRequest.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.StateEntry.FromString,
                _registered_method=True)
        self.DeleteState = channel.unary_unary(
                '/aether.server.v1.StateService/DeleteState',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.DeleteStateRequest.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.DeleteStateResponse.FromString,
                _registered_method=True)
        self.GetAllState = channel.unary_unary(
                '/aether.server.v1.StateService/GetAllState',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.GetAllStateRequest.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.GetAllStateResponse.FromString,
                _registered_method=True)


class StateServiceServicer(object):
    """============================================================
    State Service
    ============================================================

    """

    def GetState(self, request, context):
        """Get a state entry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetState(self, request, context):
        """Set a state entry (create or update)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteState(self, request, context):
        """Delete a state entry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllState(self, request, context):
        """Get all state for an actor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.GetStateRequest.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.GetStateResponse.SerializeToString,
            ),
            'SetState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetState,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.SetStateRequest.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.StateEntry.SerializeToString,
            ),
            'DeleteState': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteState,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.DeleteStateRequest.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.DeleteStateResponse.SerializeToString,
            ),
            'GetAllState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllState,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.GetAllStateRequest.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.GetAllStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aether.server.v1.StateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aether.server.v1.StateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StateService(object):
    """============================================================
    State Service
    ============================================================

    """

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.StateService/GetState',
            proto_dot_aether_dot_v1_dot_aether__pb2.GetStateRequest.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.GetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.StateService/SetState',
            proto_dot_aether_dot_v1_dot_aether__pb2.SetStateRequest.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.StateEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.StateService/DeleteState',
            proto_dot_aether_dot_v1_dot_aether__pb2.DeleteStateRequest.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.DeleteStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.StateService/GetAllState',
            proto_dot_aether_dot_v1_dot_aether__pb2.GetAllStateRequest.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.GetAllStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EventServiceStub(object):
    """============================================================
    Event / PubSub Service
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/aether.server.v1.EventService/Publish',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.PublishRequest.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.PublishResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_unary(
                '/aether.server.v1.EventService/Subscribe',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.SubscribeResponse.FromString,
                _registered_method=True)
        self.Unsubscribe = channel.unary_unary(
                '/aether.server.v1.EventService/Unsubscribe',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.UnsubscribeRequest.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.UnsubscribeResponse.FromString,
                _registered_method=True)
        self.ListTopics = channel.unary_unary(
                '/aether.server.v1.EventService/ListTopics',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.ListTopicsRequest.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.ListTopicsResponse.FromString,
                _registered_method=True)
        self.AppendEvent = channel.unary_unary(
                '/aether.server.v1.EventService/AppendEvent',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.AppendEventRequest.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.EventRecord.FromString,
                _registered_method=True)
        self.GetEvents = channel.unary_unary(
                '/aether.server.v1.EventService/GetEvents',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.GetEventsRequest.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.GetEventsResponse.FromString,
                _registered_method=True)


class EventServiceServicer(object):
    """============================================================
    Event / PubSub Service
    ============================================================

    """

    def Publish(self, request, context):
        """Publish a pub/sub message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Subscribe to a topic
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsubscribe(self, request, context):
        """Unsubscribe
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTopics(self, request, context):
        """List topics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEvent(self, request, context):
        """Append an event to an event-sourced aggregate
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvents(self, request, context):
        """Get events for an aggregate
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.PublishRequest.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.PublishResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.SubscribeRequest.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.SubscribeResponse.SerializeToString,
            ),
            'Unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsubscribe,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.UnsubscribeRequest.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.UnsubscribeResponse.SerializeToString,
            ),
            'ListTopics': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTopics,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.ListTopicsRequest.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.ListTopicsResponse.SerializeToString,
            ),
            'AppendEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEvent,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.AppendEventRequest.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.EventRecord.SerializeToString,
            ),
            'GetEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvents,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.GetEventsRequest.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.GetEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aether.server.v1.EventService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aether.server.v1.EventService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventService(object):
    """============================================================
    Event / PubSub Service
    ============================================================

    """

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.EventService/Publish',
            proto_dot_aether_dot_v1_dot_aether__pb2.PublishRequest.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.EventService/Subscribe',
            proto_dot_aether_dot_v1_dot_aether__pb2.SubscribeRequest.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.EventService/Unsubscribe',
            proto_dot_aether_dot_v1_dot_aether__pb2.UnsubscribeRequest.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.UnsubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTopics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.EventService/ListTopics',
            proto_dot_aether_dot_v1_dot_aether__pb2.ListTopicsRequest.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.ListTopicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.EventService/AppendEvent',
            proto_dot_aether_dot_v1_dot_aether__pb2.AppendEventRequest.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.EventRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.EventService/GetEvents',
            proto_dot_aether_dot_v1_dot_aether__pb2.GetEventsRequest.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.GetEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthServiceStub(object):
    """============================================================
    Health Service
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/aether.server.v1.HealthService/Health',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Ready = channel.unary_unary(
                '/aether.server.v1.HealthService/Ready',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Info = channel.unary_unary(
                '/aether.server.v1.HealthService/Info',
                request_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.InfoResponse.FromString,
                _registered_method=True)


class HealthServiceServicer(object):
    """============================================================
    Health Service
    ============================================================

    """

    def Health(self, request, context):
        """Liveness check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ready(self, request, context):
        """Readiness check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Info(self, request, context):
        """Server info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.Empty.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.HealthResponse.SerializeToString,
            ),
            'Ready': grpc.unary_unary_rpc_method_handler(
                    servicer.Ready,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.Empty.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.HealthResponse.SerializeToString,
            ),
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=proto_dot_aether_dot_v1_dot_aether__pb2.Empty.FromString,
                    response_serializer=proto_dot_aether_dot_v1_dot_aether__pb2.InfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aether.server.v1.HealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aether.server.v1.HealthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthService(object):
    """============================================================
    Health Service
    ============================================================

    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.HealthService/Health',
            proto_dot_aether_dot_v1_dot_aether__pb2.Empty.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ready(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.HealthService/Ready',
            proto_dot_aether_dot_v1_dot_aether__pb2.Empty.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aether.server.v1.HealthService/Info',
            proto_dot_aether_dot_v1_dot_aether__pb2.Empty.SerializeToString,
            proto_dot_aether_dot_v1_dot_aether__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
