apiVersion: 1

datasources:
  - name: VictoriaMetrics-US-East
    type: prometheus
    access: proxy
    url: http://victoria-metrics-us-east:8428
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"

  - name: VictoriaMetrics-EU-West
    type: prometheus
    access: proxy
    url: http://victoria-metrics-eu-west:8428
    editable: false
    jsonData:
      timeInterval: "15s"

  - name: VictoriaMetrics-AP-Southeast
    type: prometheus
    access: proxy
    url: http://victoria-metrics-ap-southeast:8428
    editable: false
    jsonData:
      timeInterval: "15s"

  - name: Loki-US-East
    type: loki
    access: proxy
    url: http://loki-us-east:3100
    editable: false

  - name: Loki-EU-West
    type: loki
    access: proxy
    url: http://loki-eu-west:3100
    editable: false

  - name: Loki-AP-Southeast
    type: loki
    access: proxy
    url: http://loki-ap-southeast:3100
    editable: false
