"""Type stubs for aether_sdk package."""

from .actor import Actor, actor
from .capabilities import Capability, CapabilitySet
from .messaging import Message, MessageType
from .state import StateHandle
from .http import HttpClient
from .exceptions import AetherError, CapabilityDenied, ActorNotFound, StateError, RpcError
from ._version import __version__

__all__: list[str]

class Actor:
    _capabilities: CapabilitySet
    _state: StateHandle | None
    _mailbox: ...
    _pending_responses: dict[str, ...]
    _running: bool
    
    @classmethod
    def name(cls) -> str: ...
    async def handle_message(self, sender: str, message: Message) -> Message | None: ...
    async def on_start(self) -> None: ...
    async def on_stop(self) -> None: ...
    def require(self, *capabilities: Capability) -> None: ...
    async def send(self, target: str, message: Message) -> None: ...
    async def call(self, target: str, request: ..., timeout: float = ...) -> ...: ...
    @property
    def state(self) -> StateHandle: ...
    async def run(self) -> None: ...
    async def stop(self) -> None: ...
    def deliver(self, sender: str, message: Message) -> None: ...

def actor(cls: type) -> type: ...
