"""Type stubs for capabilities module."""

from enum import Flag, auto
from typing import Set

class Capability(Flag):
    """Actor capabilities."""
    NETWORK_OUTBOUND: int = ...
    NETWORK_INBOUND: int = ...
    STATE_READ: int = ...
    STATE_WRITE: int = ...
    FS_READ: int = ...
    FS_WRITE: int = ...
    ACTOR_MESSAGING: int = ...
    LOG: int = ...
    TIME: int = ...
    RANDOM: int = ...
    ENVIRONMENT: int = ...
    HTTP_CLIENT: int = ...
    HTTP_SERVER: int = ...

class CapabilitySet:
    """Set of capabilities with helper methods."""
    
    _caps: Set[Capability]
    
    def __init__(self, *capabilities: Capability) -> None: ...
    
    def add(self, cap: Capability) -> None: ...
    
    def has(self, cap: Capability) -> bool: ...
    
    def has_network(self) -> bool: ...
    
    def has_state(self) -> bool: ...
